
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import ClientLayout from '@/components/ClientLayout';
import "@/app/globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'B&R 安全智能问答系统',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  sideContainer,
}: {
  children: React.ReactNode;
  sideContainer: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: '#1677ff',
              },
            }}
          >
            <ClientLayout sideContainer={sideContainer}>
              {children}
            </ClientLayout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}